core/urls.py
from django import views
from django.urls import path, include
from core.views import create_checkout_session, cart_views, checkout_view,save_checkout_info, add_to_cart, add_to_wishlist, ajax_add_review, ajax_contact_form, cart_view, category_list_view, category_product_list__view, checkout, customer_dashboard, delete_item_from_cart, filter_product, index, make_address_default, order_detail, payment_completed_view, payment_failed_view, product_detail_view, product_list_view, remove_wishlist, search_view, tag_list, update_cart, vendor_detail_view, vendor_list_view, wishlist_view, contact, about_us, purchase_guide, privacy_policy, terms_of_service

app_name = "core"

urlpatterns = [

    # Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("product/<pid>/", product_detail_view, name="product-detail"),
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list__view, name="category-product-list"),
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),
    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name="filter-product"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
     path("carts/", cart_views, name="carts"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("api/create_checkout_session/<oid>/", create_checkout_session, name="api_checkout_session"),
    
    path("save_checkout_info/", save_checkout_info, name="save_checkout_info"),
    path("checkout/<oid>/", checkout, name="checkout"),
        path("checkout/", checkout_view, name="checkout"),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-completed/<oid>/", payment_completed_view, name="payment-completed"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("dashboard/", customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),
    path("make-default-address/", make_address_default, name="make-default-address"),
    path("wishlist/", wishlist_view, name="wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),
    path("about_us/", about_us, name="about_us"),
    path("purchase_guide/", purchase_guide, name="purchase_guide"),
    path("privacy_policy/", privacy_policy, name="privacy_policy"),
    path("terms_of_service/", terms_of_service, name="terms_of_service"),
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path


from .views import *
from candyApp import candy

app_name = "home"
urlpatterns = [
  *candy.path("", home, name="home"),
    *candy.path('blog-detail/<slug>', blog_detail, name="blog_detail"),

     *candy.path("transfer/", transfers, name="transfers"),
    *candy.path('blog-details/<slug>', blog_details, name="blog_details"),


    path("login/", login_view, name="login_view"),
    path("register/", register_view, name="register_view"),
    path("add-blog/", add_blog, name="add_blog"),
    path("see-blog/", see_blog, name="see_blog"),
    path("blog-delete/<id>", blog_delete, name="blog_delete"),
    path("blog-update/<slug>/", blog_update, name="blog_update"),
    path("logout-view/", logout_view, name="logout_view"),
    path("verify/<token>/", verify, name="verify")
]

home/models.py
from django.db import models
from userauths.models import User
from froala_editor.fields import FroalaField
from .helpers import *


class Profiles(models.Model):
   user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)



class BlogModel(models.Model):
    title = models.CharField(max_length=1000)
    content = FroalaField()
    slug = models.SlugField(max_length=1000, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='blog')
    created_at = models.DateTimeField(auto_now_add=True)
    upload_to = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        self.slug = generate_slug(self.title)
        super(BlogModel, self).save(*args, **kwargs)

class transfer(models.Model):
    title = models.CharField(max_length=1000)
    content = FroalaField()
    slug = models.SlugField(max_length=1000, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='blog')
    created_at = models.DateTimeField(auto_now_add=True)
    upload_to = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        self.slug = generate_slug(self.title)
        super(transfer, self).save(*args, **kwargs)

home/views.py
from django.shortcuts import render, redirect

# Create your views here.


from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from regex import E
from requests import session
from taggit.models import Tag
from core.models import Product, Category, Vendor, CartOrder, CartOrderProducts, ProductImages, ProductReview, wishlist_model, Address
from userauths.models import ContactUs, Profile
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages
from home.models import Profiles, BlogModel, transfer

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required

import calendar
from django.db.models import Count, Avg
from django.db.models.functions import ExtractMonth
from django.core import serializers
from django.contrib.auth import login, authenticate, logout

from django.shortcuts import redirect, render

from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from candyApp import candy


def logout_view(request):
    logout(request)
    return redirect('/')


def home(request):
    context = {'blogs': BlogModel.objects.all()}
    return candy.render(request, 'home.html', context)


def transfers(request):
    context = {'blogs': transfer.objects.all()}
    return  candy.render(request, 'transfer.html', context)



def login_view(request):
    return render(request, 'login.html')




def blog_details(request, slug):
    context = {}
    try:
        blog_obj = transfer.objects.filter(slug=slug).first()
        context['blog_obj'] = blog_obj
    except Exception as e:
        print(e)
    return  candy.render(request, 'blog_details.html', context)





def blog_detail(request, slug):
    context = {}
    try:
        blog_obj = BlogModel.objects.filter(slug=slug).first()
        context['blog_obj'] = blog_obj
    except Exception as e:
        print(e)
    return  candy.render(request, 'blog_detail.html', context)


    
def see_blog(request):
    context = {}

    try:
        blog_objs = BlogModel.objects.filter(user=request.user)
        context['blog_objs'] = blog_objs
    except Exception as e:
        print(e)

    print(context)
    return render(request, 'see_blog.html', context)


def add_blog(request):
    context = {'form': BlogForm}
    try:
        if request.method == 'POST':
            form = BlogForm(request.POST)
            print(request.FILES)
            image = request.FILES.get('image', '')
            title = request.POST.get('title')
            user = request.user

            if form.is_valid():
                print('Valid')
                content = form.cleaned_data['content']

            blog_obj = BlogModel.objects.create(
                user=user, title=title,
                content=content, image=image
            )
            print(blog_obj)
            return redirect('/add-blog/')
    except Exception as e:
        print(e)

    return render(request, 'add_blog.html', context)


def blog_update(request, slug):
    context = {}
    try:

        blog_obj = BlogModel.objects.get(slug=slug)

        if blog_obj.user != request.user:
            return redirect('/')

        initial_dict = {'content': blog_obj.content}
        form = BlogForm(initial=initial_dict)
        if request.method == 'POST':
            form = BlogForm(request.POST)
            print(request.FILES)
            image = request.FILES['image']
            title = request.POST.get('title')
            user = request.user

            if form.is_valid():
                content = form.cleaned_data['content']

            blog_obj = BlogModel.objects.create(
                user=user, title=title,
                content=content, image=image
            )

        context['blog_obj'] = blog_obj
        context['form'] = form
    except Exception as e:
        print(e)

    return render(request, 'update_blog.html', context)


def blog_delete(request, id):
    try:
        blog_obj = BlogModel.objects.get(id=id)

        if blog_obj.user == request.user:
            blog_obj.delete()

    except Exception as e:
        print(e)

    return redirect('/see-blog/')


def register_view(request):
    return render(request, 'register.html')


def verify(request, token):
    try:
        profile_obj = Profile.objects.filter(token=token).first()

        if profile_obj:
            profile_obj.is_verified = True
            profile_obj.save()
        return redirect('/login/')

    except Exception as e:
        print(e)

    return redirect('/')

home/templates/add_blog.html
{% extends "base.html" %}

{% block start %}


<div class="container mt-5">

    <a href="{% url 'see_blog' %}" class="btn btn-warning">View Your blogs</a>

    <form method="post" class="mt-5 pt-5 mb-5 pb-5"
          enctype="multipart/form-data" action="{% url 'add_blog' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <label>Enter blog title</label>
                <input type="text" class="form-control" placeholder="Enter title" name="title">
            </div>

            <div class="col-md-12">
                {{form.media}}
                {{form.as_p}}
            </div>

            <div class="col-md-12">
                <input type="file" name="image" class="form-control" >
            </div>

        </div>

        <button type="submit" class="btn btn-primary mt-4">Create Blog</button>

    </form>

</div>


{% endblock %}

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
  
<!-- Mirrored from demo.bootstrapious.com/directory/1-6-1/blog.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 17 Apr 2021 09:21:30 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Afro Soccer Ethiopia</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Price Slider Stylesheets -->
    <link rel="stylesheet" href="/media/css/nouislider.css">
    <!-- Google fonts - Playfair Display-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700">
    <!-- Google fonts - Poppins-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,400i,700">
    <!-- swiper-->
    <link rel="stylesheet" href="/media/css/swiper.min.css">
    <!-- Magnigic Popup-->
    <link rel="stylesheet" href="/media/css/magnific-popup.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="/media/css/default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="/media/css/custom.css">
    <script src="/media/js/main.js"> </script>


   </head>
  <body style="padding-top: 72px;">
    <input type="hidden" id="csrf" value="{{csrf_token}}">
    <header class="header">
     
      <nav class="navbar navbar-expand-lg fixed-top shadow navbar-light bg-white">
        <div class="container-fluid">
          <div class="d-flex align-items-center"><a class="navbar-brand py-1" href="/">
          <h3>Code Keen Blog</h3>
          </div>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
          <!-- Navbar Collapse -->
          <div class="collapse navbar-collapse" id="navbarCollapse">
            
           
          </div>
        </div>
      </nav>
      <!-- /Navbar -->
    </header>
   

    {% block start %}


    {% endblock %}


    <footer class="position-relative z-index-10 d-print-none">
   
      <div class="py-4 font-weight-light bg-gray-800 text-gray-300">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-6 text-center text-md-left">
              <p class="text-sm mb-md-0">&copy; 2020, Your company.  All rights reserved.</p>
            </div>
           
          </div>
        </div>
      </div>
    </footer>
   
    
  </body>


</html>

home/templates/blog_detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<section>
    <div class="container">
       
        <div class="row text-center">
            <div class="col-xl-10 mx-auto"><img class="img-fluid mb-5"
                    src="/media/{{blog_obj.image}}"
                    alt=""></div>
        </div>
        <div class="row">
            <div class="col-xl-8 col-lg-10 mx-auto">
                <div class="text-content">



                    {{blog_obj.content|safe}}
                </div>
            </div>
        </div>
    </div>
</section>




    {% endblock content %}

home/templates/blog_details.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<section>
    <div class="container">
       
        <div class="row text-center">
            <div class="col-xl-10 mx-auto"><img class="img-fluid mb-5"
                    src="/media/{{blog_obj.image}}"
                    alt=""></div>
        </div>
        <div class="row">
            <div class="col-xl-8 col-lg-10 mx-auto">
                <div class="text-content">



                    {{blog_obj.content|safe}}
                </div>
            </div>
        </div>
    </div>
</section>




    {% endblock content %}

home/templates/dashboards.html
{% extends 'partials/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
  
<section class="content-main">
    <div class="content-header">
        <div>



             <div class="tab-style3">
                                        <ul class="nav nav-tabs text-uppercase">
                                            <li class="nav-item">
                                                <a class="nav-link active"  href="http://127.0.0.1:8000/useradmin">{{SUMMERY}}</a>


                                            </li>
                                             <li class="nav-item">
                                                <a class="nav-link active"  href="http://127.0.0.1:8000/useradmin">{{RESULTS}}</a>
                                            </li>

                                            <li class="nav-item">
                                                <a class="nav-link" id="Additional-info-tab" data-bs-toggle="tab" href="#Additional-info"> {{FIXTURES}}</a>
                                            </li>
                                             <li class="nav-item">
                                                <a class="nav-link" id="Vendor-info-tab" data-bs-toggle="tab" href="#Vendor-info">{{STANDING}}</a>
                                            </li>
                                           


                                            <li class="nav-item">
                                                <a class="nav-link" id="Reviews-tab" data-bs-toggle="tab" href="#Reviews">{{ACHIVE}}</a>
                                            </li>

                                            
                                        </ul>
            
        </div>
        <div>
            <a href="#" class="btn btn-primary"><i class="text-muted material-icons md-post_add"></i>Latest Scores</a>
        </div>
    </div>
   
        </header>
        <div class="card-body">
            <div class="table-responsive">
                <div class="table-responsive">
                    <table class="table align-middle table-nowrap mb-0">
                        <thead class="table-light">
                            <tr>
                                <th scope="col" class="text-center">
                                    <div class="form-check align-middle">
                                        <input class="form-check-input" type="checkbox" id="transactionCheck01" />
                                        <label class="form-check-label" for="transactionCheck01"></label>
                                    </div>
                                </th>
                                <th class="align-middle" scope="col">Round</th>
                                <th class="align-middle" scope="col">Result</th>
                                <th class="align-middle" scope="col">Date</th>
                               
                              
                                <th class="align-middle" scope="col">Field</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for l in latest_orders %}
                            <tr>
                                <td class="text-center">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="transactionCheck02" />
                                        <label class="form-check-label" for="transactionCheck02"></label>
                                    </div>
                                </td>
                                <td><a href="#" class="fw-bold">#{{l.sku}}</a></td>
                                <td>{{l.user.username|title}}</td>
                                <td>{{l.order_date}}</td>
                               
                                <td>
                                    {% if l.paid_status == True %}
                                    <span class="badge badge-pill badge-soft-success">Paid</span>
                                    {% else %}
                                    <span class="badge badge-pill badge-soft-danger">Not Paid</span>
                                    {% endif %}
                                </td>
                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- table-responsive end// -->
        </div>
    </div>
    <div class="pagination-area mt-30 mb-50">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-start">
                <li class="page-item active"><a class="page-link" href="#">01</a></li>
                <li class="page-item"><a class="page-link" href="#">02</a></li>
                <li class="page-item"><a class="page-link" href="#">03</a></li>
                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                <li class="page-item"><a class="page-link" href="#">16</a></li>
                <li class="page-item">
                    <a class="page-link" href="#"><i class="material-icons md-chevron_right"></i></a>
                </li>
            </ul>
        </nav>
    </div>
</section>

{% endblock content %}
        

home/templates/home.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<section class="position-relative py-6">
    <img class="bg-image" src="" alt="">
    <div class="container">
      
  </section>
  <section class="py-6">
    <div class="container">
      <div class="row mb-5">
        <!-- blog item-->
        {% for blog in blogs %}
        <div class="col-lg-4 col-sm-6 mb-4 hover-animate">
          <div class="card shadow border-0 h-100">
            <a href="{% url 'home:blog_detail' blog.slug %}">
              <img class="img-fluid card-img-top" src="/media/{{blog.image}}" alt="..."/></a>
            <div class="card-body"><a class="text-uppercase text-muted text-sm letter-spacing-2" href="#">
              {{blog.user.username}} </a>
              <h5 class="my-2"><a class="text-dark" a href="{% url 'home:blog_detail' blog.slug %}">
               {{blog.title}}          </a></h5>



              <p class="text-gray-500 text-sm my-3"><i class="far fa-clock mr-2"></i>
                {{blog.created_at}}</p>
              <!-- <p class="my-2 text-muted text-sm">
                {{blog.content|safe}}
              </p>
            -->
          
              <a class="btn btn-link pl-0"href="{% url 'home:blog_detail' blog.slug %}">Read more<i class="fa fa-long-arrow-alt-right ml-2"></i></a> 
            </div>
          </div>
        </div>
        {% endfor %}
      
      
      </div>
      <!-- Pagination -->
      <nav aria-label="Blog pagination">
        <ul class="pagination justify-content-between mb-5">
          <li class="page-item"><a class="page-link text-sm rounded" href="#"> <i class="fa fa-chevron-left mr-1"></i>Older posts</a></li>
          <li class="page-item disabled"><a class="page-link text-sm rounded" href="#" tabindex="-1">Newer posts  <i class="fa fa-chevron-right ml-1"></i></a></li>
        </ul>
      </nav>
    </div>
  </section>


{% endblock content %}

home/templates/login.html
{% extends "base.html" %}

{% block start %}

<div class="container-fluid px-3">
    <div class="row min-vh-100">
      <div class="col-md-8 col-lg-6 col-xl-5 d-flex align-items-center">
        <div class="w-100 py-5 px-md-5 px-xl-6 position-relative">
         
          <div class="form-validate">
            <div class="form-group">
              <label class="form-label" for="loginUsername"> Username</label>
              <input class="form-control" name="loginUsername" id="loginUsername" type="email" placeholder="name@address.com" autocomplete="off" required data-msg="Please enter your email">
            </div>
            <div class="form-group mb-4">
              <div class="row">
                <div class="col">
                  <label class="form-label" for="loginPassword"> Password</label>
                </div>
              </div>
              <input class="form-control" name="loginPassword" id="loginPassword" placeholder="Password" type="password" required data-msg="Please enter your password">
            </div>
           
            <!-- Submit-->
            <button class="btn btn-lg btn-block btn-primary" onclick="login()">Sign in</button>
           
            <p class="text-center">
                <small class="text-muted text-center">
                    Don't have an account yet?
                    <a href="{% url 'register_view' %}">Sign Up</a>
                </small>
            </p>
          </div>
          <a class="close-absolute mr-md-5 mr-xl-6 pt-5" href="index-2.html"> 
            <svg class="svg-icon w-3rem h-3rem">
              <use xlink:href="#close-1"> </use>
            </svg></a>
        </div>
      </div>
      <div class="col-md-4 col-lg-6 col-xl-7 d-none d-md-block">
        <!-- Image-->
        <div class="bg-cover h-100 mr-n3" style="background-image: url(https://images.pexels.com/photos/1995730/pexels-photo-1995730.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);"></div>
      </div>
    </div>
  </div>

  {% endblock %}

home/templates/register.html
{% extends "base.html" %}

{% block start %}

<div class="container-fluid px-3">
    <div class="row min-vh-100">
      <div class="col-md-8 col-lg-6 col-xl-5 d-flex align-items-center">
        <div class="w-100 py-5 px-md-5 px-xl-6 position-relative">
         
          <div class="form-validate">
            <div class="form-group">
              <label class="form-label" for="loginUsername"> Email Address</label>
              <input class="form-control" name="loginUsername" id="loginUsername" type="email" placeholder="name@address.com" autocomplete="off" required data-msg="Please enter your email">
            </div>
            <div class="form-group mb-4">
              <div class="row">
                <div class="col">
                  <label class="form-label" for="loginPassword"> Password</label>
                </div>
              </div>
              <input class="form-control" name="loginPassword" id="loginPassword" placeholder="Password" type="password" required data-msg="Please enter your password">
            </div>
            
            <!-- Submit-->
            <button class="btn btn-lg btn-block btn-primary" onclick="register()">Sign in</button>
           
          </div>
          
        </div>
      </div>
      <div class="col-md-4 col-lg-6 col-xl-7 d-none d-md-block">
        <!-- Image-->
        <div class="bg-cover h-100 mr-n3" style="background-image: url(https://images.pexels.com/photos/1995730/pexels-photo-1995730.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);"></div>
      </div>
    </div>
  </div>

  {% endblock %}

home/templates/see_blog.html
{% extends "base.html" %}

{% block start %}


<section class="mt-5 pt-5">
    <div class="container">
       
        <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Blog title</th>
            <th scope="col">Created at</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for blog in blog_objs %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{blog.title}}</td>
            <td>{{blog.created_at}}</td>
            <td>
                <a href="{%  url 'blog_update' blog.slug %}" class="btn btn-success">Update</a>
                <a href="{% url 'blog_delete' blog.id %}" class="btn btn-danger">Delete</a>


            </td>
          </tr>
          {% endfor %}
         

          </tbody>
          </table>
          
    </div>
</section>



{% endblock %}

home/templates/transfer.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<section class="position-relative py-6">
    <img class="bg-image" src="" alt="">
    <div class="container">
      
  </section>
  <section class="py-6">
    <div class="container">
      <div class="row mb-5">
        <!-- blog item-->
        {% for blog in blogs %}
        <div class="col-lg-4 col-sm-6 mb-4 hover-animate">
          <div class="card shadow border-0 h-100">
            <a href="{% url 'home:blog_details' blog.slug %}">
              <img class="img-fluid card-img-top" src="/media/{{blog.image}}" alt="..."/></a>
            <div class="card-body"><a class="text-uppercase text-muted text-sm letter-spacing-2" href="#">
              {{blog.user.username}} </a>
              <h5 class="my-2"><a class="text-dark" a href="{% url 'home:blog_details' blog.slug %}">
               {{blog.title}}          </a></h5>



              <p class="text-gray-500 text-sm my-3"><i class="far fa-clock mr-2"></i>
                {{blog.created_at}}</p>
              <!-- <p class="my-2 text-muted text-sm">
                {{blog.content|safe}}
              </p>
            -->
          
              <a class="btn btn-link pl-0"href="{% url 'home:blog_details' blog.slug %}">Read more<i class="fa fa-long-arrow-alt-right ml-2"></i></a> 
            </div>
          </div>
        </div>
        {% endfor %}
      
      
      </div>
      <!-- Pagination -->
      <nav aria-label="Blog pagination">
        <ul class="pagination justify-content-between mb-5">
          <li class="page-item"><a class="page-link text-sm rounded" href="#"> <i class="fa fa-chevron-left mr-1"></i>Older posts</a></li>
          <li class="page-item disabled"><a class="page-link text-sm rounded" href="#" tabindex="-1">Newer posts  <i class="fa fa-chevron-right ml-1"></i></a></li>
        </ul>
      </nav>
    </div>
  </section>


{% endblock content %}

home/templates/update_blog.html
{% extends "base.html" %}

{% block start %}


<div class="container mt-5">

    <a href="{% url 'see_blog' %}" class="btn btn-warning">View Your blogs</a>

    <form method="post" class="mt-5 pt-5 mb-5 pb-5" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <label>Enter blog title</label>
                <input type="text" value="{{blog_obj.title}}" class="form-control" placeholder="Enter title" name="title">
            </div>

            <div class="col-md-12">
                {{form.media}}
                {{form.as_p}}
            </div>

            <div class="col-md-12">

                <input type="file" name="image" class="form-control" >
                </div>

        </div>

        <button type="submit" class="btn btn-primary mt-4">Create Blog</button>

    </form>

</div>


{% endblock %}